startupanimation:startupanimation.o
	qcc -Vgcc_ntoarmv7le -o startupanimation startupanimation.o
startupanimation.o:startupanimation.c
	qcc -Vgcc_ntoarmv7le -c startupanimation.c
clean:
	rm startupanimation startupanimation.o
